name: fitmate
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  firebase_auth_web: ^5.12.0
  cloud_firestore: ^4.14.0
  intl: ^0.19.0
  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  percent_indicator: ^4.2.4
  http: ^1.3.0
  shared_preferences: ^2.5.2
  cached_network_image: ^3.3.0
  firebase_storage: ^11.7.7
  flutter_riverpod: ^2.6.1
  lottie: ^3.3.1
  image: ^4.1.7
  image_picker: ^0.8.4+4
  google_fonts: ^6.1.0
  provider: ^6.0.5
  url_launcher: ^6.1.7
  flutter_launcher_icons: ^0.14.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth_mocks: ^0.13.0
  mockito: ^5.4.4
  fake_cloud_firestore: ^2.4.8
  build_runner: ^2.4.8
  test: ^1.24.9
  flutter_lints: ^3.0.1
  firebase_core_platform_interface: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/data/images/fit_robot.png
    - assets/data/images/strawberry.png
    - assets/data/images/workouts/image 2.png
    - assets/data/images/workouts/image 3.png
    - assets/data/images/workouts/image 4.png
    - assets/data/images/workouts/image 5.png
    - assets/data/images/yoga-pose.png
    - assets/data/images/avatar/1.jpg
    - assets/data/images/avatar/2.jpg
    - assets/data/images/avatar/3.jpg
    - assets/data/images/avatar/4.jpg
    - assets/data/images/avatar/5.jpg
    - assets/data/images/avatar/6.jpg
    - assets/data/lottie/1.json
    - assets/data/lottie/2.json
    - assets/data/lottie/3.json
    - assets/data/lottie/4.json
    - assets/data/images/food/
    - assets/data/lottie/5.json
