name: fitmate
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

# dependencies:
#   flutter:
#     sdk: flutter


#   cupertino_icons: ^1.0.8

#   # Firebase dependencies
#   firebase_core: ^3.8.0
#   firebase_auth: ^5.3.3
#   firebase_auth_web: ^5.13.4
#   cloud_firestore: ^5.5.0
  
# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   firebase_auth_mocks: ^0.14.1
#   mockito: ^5.4.0
#   fake_cloud_firestore: ^3.1.0
#   build_runner: ^2.4.0
#   test: any
#   google_fonts: ^6.2.1
#   flutter_lints: ^5.0.0
#   firebase_core_platform_interface: ^5.0.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.17.5
  firebase_auth: ^4.20.0
  firebase_auth_web: ^5.12.0
  cloud_firestore: ^4.14.0
  intl: ^0.19.0
  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  percent_indicator: ^4.2.4
  http: ^1.3.0
  shared_preferences: ^2.5.2
  cached_network_image: ^3.3.0
  #sharifa
  #tflite_flutter: ^0.9.0  # Runs TFLite models
  image: ^4.1.7  # Used to resize and normalize images before inference
  image_picker: ^0.8.4+4



dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth_mocks: ^0.13.0
  mockito: ^5.4.4
  fake_cloud_firestore: ^2.4.8
  build_runner: ^2.4.8
  test: ^1.24.9
  google_fonts: ^6.1.0
  flutter_lints: ^3.0.1
  firebase_core_platform_interface: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/data/images/fit_robot.png
    - assets/data/images/strawberry.png
    - assets/data/images/workouts/image 2.png
    - assets/data/images/workouts/image 3.png
    - assets/data/images/workouts/image 4.png
    - assets/data/images/workouts/image 5.png
    - assets/data/images/yoga-pose.png
  #sharifa
  #  - assets/models/food_model.tflite


  
